<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>../icon/app/256x256.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="../icon/on/32x32.ico"><LogicalName>icon.on.32x32.ico</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="../icon/on/16x16.ico"><LogicalName>icon.on.16x16.ico</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="../icon/off/32x32.ico"><LogicalName>icon.off.32x32.ico</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="../icon/off/16x16.ico"><LogicalName>icon.off.16x16.ico</LogicalName></EmbeddedResource>
  </ItemGroup>

</Project>